# Site settings
title: "Anthony's Thoughts"                  # The title of your blog
description: "A blog about XYZ."  # A short description of your blog
baseurl: "/blog"                  # Subdirectory where your blog resides
url: "https://huaanthony.com/" # Your GitHub Pages URL (or custom domain)

# Markdown processing
markdown: kramdown                # Use kramdown for Markdown processing

# Permalinks
permalink: /blog/:title/          # Customize post URLs  # URL structure for posts

defaults:
  - scope:
      path: "_posts"
    values:
      layout: post              # Default layout for posts

# Exclude non-blog parts of your site
exclude:
  - ../*                         # Prevent processing of non-blog files
