# Site settings
title: "Anthony's Thoughts"                  # The title of your blog
description: "A blog about XYZ."  # A short description of your blog
baseurl: "/blog"                  # Subdirectory where your blog resides
url: "https://huaanthony.com/" # Your GitHub Pages URL (or custom domain)

# Markdown processing
markdown: kramdown                # Use kramdown for Markdown processing

# Directory settings
source: .                         # Use the current directory as the source
destination: ../docs/blog         # Output the blog to the GitHub Pages `docs/blog` folder

# Permalinks
permalink: /:categories/:title/   # URL structure for posts

# Collections
collections:
  posts:
    output: true                  # Enable posts output

# Defaults
defaults:
  - scope:
      path: "_posts"             # Apply defaults only to posts
    values:
      layout: post
      author: "Your Name"

# Exclude non-blog parts of your site
exclude:
  - ../*                         # Prevent processing of non-blog files
  - .nojekyll                    # Ignore the `.nojekyll` file
