backend:
  name: git-gateway
  branch: main  # Change this to your default Git branch
  repo: anthualib/vanitysite
  api_root: https://api.github.com
  base_url: https://api.netlify.com

site_url: https://huaanthony.com

media_folder: "/images/uploads" # Where uploaded images will go
public_folder: "/images/uploads"     # Public path to uploaded images

collections:
  - name: "blog"         # Name of the collection
    label: "Blog Posts"  # Label in the CMS UI
    folder: "_posts/blog" # Path to the folder where content files are stored
    create: true          # Allow users to create new entries
    slug: "{{slug}}"      # Filename template for new posts
    fields:               # Fields for each entry
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }
